### ISSUE TITLE
Crash to desktop when loading into world. Only happens when using Java 12 and up.

### ISSUE THREAD

**Issue by dmsw0303** [team-abnormals/personality#14]
Editing post to help others that are experiencing this issue. Keybinds aren't initialized properly when using a runtime above java 12. And hence game wont show them when loaded, and will crash when trying to play

**Comment by dmsw0303** [comment]
https://gist.githubusercontent.com/natanfudge/7d01c4034d27392257c7c015d236366c/raw/f5b17186a139d5580376d98d3059f455200bf3e9/crash.txt

almost forgot. sorry about that

**Comment by JacksonPlayz** [comment]
Fixed in 879a0eafb40b95e7d2cfabcca47c91e9ca11184d
