### ISSUE TITLE
1.17.1 forge is out

### ISSUE THREAD

**Issue by EnderHunter14** [team-abnormals/personality#23]
1.17.1 forge is out, so can you update it to 1.17.1?

**Comment by bageldotjpg** [comment]
1) Forge 1.17.1 is an insanely early and fragile state, it is very broken.
2) It does not include Mixins, which this mod relies on. So we literally can not port.
3) Abnormals Core also has Mixins, and thus can not port either.
4) It hasn't even been a *week*. It takes time to port and test.

We will not be starting until Forge 1.17 is more stable and has support for mixins.
Have some respect.
