### ISSUE TITLE
What Is This?!?

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [team-abnormals/personality#40]
What is this mod?!?  Like, seriously, all of your mod descriptions have this problem to one degree or another, but this one is probably the worst!  Your curseforge mod pages have great little teaser intros, beautiful little bite sized that can quickly give someone a vague idea of what the mod is about, a good hook to draw one in.  The problem is that that's all there is!  Intros are followed by bodies and then conclusions for a reason, not having the rest is like having a wonderfully baited hook, with no line attached to it.  It's ultimately pointless.

What, exactly, and in at least a modicum of detail, does this mod do?  Because unless and until I know that, I'm not going to bother going though the hassle of downloading it and getting it to work with all my other mods, I'd rather take the easy way out and just ignore it...

**Comment by bageldotjpg** [comment]
The CurseForge page actually completely describes the mod - there is just a crawling keybind, a sitting keybind, and a climbing animation.
