### ISSUE TITLE
Mod supports 1.19.4 but dependancy does not

### ISSUE THREAD

**Issue by Solesteam** [team-abnormals/personality#44]
So the mod has support for 1.19.3 and 1.19.4 but Blueprint only supports 1.19.2 before skipping to 1.20 the mod can't load without it but with it it crashes regardless due to the version mismatch. saying: 
"Mod ID: 'minecraft', Requested by: 'blueprint', Expected range: '[1.19.2,1.19.3)', Actual version: '1.19.4'"

**Comment by bageldotjpg** [comment]
This was a mislabel - the mod doesn't support 1.19.4. The file listening has been fixed.
