### ISSUE TITLE
Sitting animation broken in modded seats

### ISSUE THREAD

**Issue by COLDW0LF** [team-abnormals/personality#9]
As title suggests; the same issue as with boats (#5) exists when sitting in a chair or seat from mods such as Create.

**Comment by JacksonPlayz** [comment]
If you read the issue that was linked, this is fixed in dev.

**Comment by COLDW0LF** [comment]
Awesome, thanks.
I figured it might be but wasn't sure if the issue was an identical solution, so thought I'd offer a heads up anyway.
